### ISSUE TITLE
How to train a slumbot for heads-up no-limit Texas Holdem?

### ISSUE THREAD

**Issue by kli-nlpr** [ericgjackson/slumbot2019#2]
Dear @ericgjackson 
I am wondering how to use your code to train a bot to play heads-up no-limit Texas Holdem (like this one www.slumbot.com)
There are lot of code in this repo, I want to have an intuitive understanding of the project by training a heads-up no-limit Texas Holdem bot step by step.
Thank you very much! O(∩_∩)O

**Comment by ericgjackson** [comment]
As you say, there is a lot of code in the repository, which can make it
difficult to get started.  The code base is trying to be very full featured
and general, which tends to obscure some of the basics.  A couple of ideas:

1) Start with a simpler code base.  You can find Kevin Waugh's sample code
for solving a simple poker game here:
http://poker.cs.ualberta.ca/open_cfr.html.  You can find Rich Gibson's code
here: https://github.com/rggibson/open-pure-cfr.

2) If sticking with this repository, maybe trace through what happens with
a simple game.  The README.md gives steps for solving a game I call
"ms1f3".  (It's a simple two street Holdem variant with three cards on the
flop.)  Focus on how regrets are updated and the "sumprobs".  The relevant
code will mostly be in vcfr.cpp and cfr_utils.cpp.

You might want to read about CFR first, although I don't know of a good
introduction to point you to.  Some of the published papers might be too
technical and too theoretical to start with.

**Comment by kli-nlpr** [comment]
Thanks，I will check ms1f3 first
