### ISSUE TITLE
Slumbot does not raise the nuts on the river

### ISSUE THREAD

**Issue by JbCourtois** [ericgjackson/slumbot2019#25]
![2022-08-24 0100](https://user-images.githubusercontent.com/9624476/186282556-ff1bfa77-2536-4775-82f5-109cde47b341.jpg)

NB: this is a custom UI I developed. You can find the source code here: https://github.com/JbCourtois/SlumbotUI

**Comment by JbCourtois** [comment]
![2022-08-24 0100](https://user-images.githubusercontent.com/9624476/186282556-ff1bfa77-2536-4775-82f5-109cde47b341.jpg)

**Comment by ericgjackson** [comment]
Yeah, this is a limitation of Slumbot's betting abstraction.  It doesn't have a good model of how to respond to that last bet of 7200.  In the betting state b250c/kk/b250b800b2750c/b3000, the abstraction allows a call or an all-in, but not any bet size in the middle.
