### ISSUE TITLE
build_betting_tree

### ISSUE THREAD

**Issue by kli-nlpr** [ericgjackson/slumbot2019#3]
Hi, @ericgjackson  I am wondering what’s the purpose of build_betting_tree?

Can you give an Intuitive example of the betting tree?
i.e., after executing ../bin/build_betting_tree ms1f3_params mb1b1_params
What has been saved on the disk?

Thanks

**Comment by ericgjackson** [comment]
It stores a representation of all the "betting paths" the players can
take.  For example, one path might be a preflop pot-size opening bet,
followed by a call, followed by a flop check-check.  The "betting tree" is
the tree that represents all those paths.

You can run show_betting_tree to see the betting tree (nothing fancy, just
a text representation of the tree).

**Comment by kli-nlpr** [comment]
Thanks, I got it!

**Comment by kli-nlpr** [comment]
I run the show_betting_tree
The output looks like this
```
"BC BC CBF" (id 153 lbt 18 ns 0 st 2 p1c)
          "BC BC B" (id 17 lbt 54 ns 2 st 2 p1c)
            "BC BC BC" (id 52 lbt 54 ns 2 st 3 p0c)
              "BC BC BC C" (id 52 lbt 54 ns 2 st 3 p1c)
                "BC BC BC CC" (id 154 lbt 54 ns 0 st 3)
```
I know `st` represents street
But I cannot figure out what's the meaning of `id,ldt,ns,p*c`

**Comment by ericgjackson** [comment]
"ns" is the number of "successors"; i.e., the number of children of this
node corresponding to actions you can take.  There might be one or more bet
successors, a fold successor, a call successor...
"p1c" means player 1 choice - i.e, player 1 acts here; "p0c" means player 0
acts here.  Player 1 is the button, player 0 is the big blind.
"lbt" stands for "last bet to" - the total number of chips put into the pot
by the last bettor.  Not just the last bet, includes chips put into the pot
on all streets.  The big blind is considered to be 2 chips.
"id" is just "ID".  A number assigned to every node.  IDs are unique for a
given player on a given street.

**Comment by kli-nlpr** [comment]
Thank you very much for your patience to answer
