### ISSUE TITLE
mp_betting_tree CreateMPStreet error

### ISSUE THREAD

**Issue by ZHANGTIANHE** [ericgjackson/slumbot2019#33]
Hello, 
Is it a bug in mp_betting_tree.cpp line 429 
i check when calling CreateMPStreet, street will add 1 outside, so is it unnessasary to add 1 again?
i think the right code is below
int next_player_to_act = NextPlayerToAct(Game::FirstToAct(street), folded)
while old code is
int next_player_to_act =NextPlayerToAct(Game::FirstToAct(street + 1), folded);

**Comment by ericgjackson** [comment]
Yes, your change looks correct.  I will fix.  Thanks.

**Comment by ZHANGTIANHE** [comment]
Thanks for the awesome project
