### ISSUE TITLE
Bug on Straight Flush Winning Calculation ? 

### ISSUE THREAD

**Issue by 2bco** [ericgjackson/slumbot2019#39]
Hi, i tested my bot against your API on slumbot.com and found this strange hand in my records. 
My Hand:  8H high straight flush loosing against an AK with (no Joke)   3H 4H 5H 6H 7H  board . Here are my records 

{
  "_id": {
    "$oid": "6663331f4a6fab7a117f02b0"
  },
  "name": "D",
  "date": {
    "$date": "2024-06-07T16:19:43.358Z"
  },
  "bb": 100,
  "sb": 50,
  "pot": 40000,
  "streets": 0,
  "showDown": true,
  "players": [
    {
      "_user": {
        "$oid": "6658806b4ff4dcb254aa5eec"
      },
      "name": "SlumBot",
      "money": 20000,
      "pocket": [
        "AD",
        "KC"
      ],
      "winning": 20000
    },
    {
      "_user": {
        "$oid": "657ad579ebf85d7bd01395ad"
      },
      "name": "trainer",
      "money": 20000,
      "pocket": [
        "8H",
        "8D"
      ],
      "winning": 0
    }
  ],
  "actions": [
    "p0r150",
    "p1r700",
    "p0r2200",
    "p1r8800",
    "p0r17600",
    "p1c"
  ],
  "actionString": "b200b800b2400b9600b20000c///",
  "board": [
    "3H",
    "4H",
    "5H",
    "6H",
    "7H"
  ],
  "__v": 0
}

**Comment by ericgjackson** [comment]
I'm having trouble finding this hand in the logs.  Can you tell me:
1) What day was the hand played on the site?  Was it 6/7/2024?
2) What username were you playing under?

**Comment by 2bco** [comment]
Hi Eric the username is pokerheads, and the time the game was dealt is "2024-06-07T16:19:43.358Z" utc

**Comment by 2bco** [comment]
i played on June 7. 1000 more games , almost everything i reviewd made sense. i found only one hand again was strange wrong 
. This time again a straight flush on the board  9-K of hearts with AH in your pocket , and another 9H in my pocket 
this is the hand :  


"_id": {
      "$oid": "6663343d4a6fab7a117f05ca"
    },
    "name": "D",
    "date": {
      "$date": "2024-06-07T16:24:29.708Z"
    },
    "bb": 100,
    "sb": 50,
    "pot": 40000,
    "streets": 0,
    "showDown": true,
    "players": [
      {
        "_user": {
          "$oid": "6658806b4ff4dcb254aa5eec"
        },
        "name": "SlumBot",
        "money": 20000,
        "pocket": [
          "AH",
          "KS"
        ],
        "winning": 20000
      },
      {
        "_user": {
          "$oid": "657ad579ebf85d7bd01395ad"
        },
        "name": "trainer",
        "money": 20000,
        "pocket": [
          "9H",
          "9D"
        ],
        "winning": 0
      }
    ],
    "actions": [
      "p0r150",
      "p1r700",
      "p0r2200",
      "p1r8800",
      "p0r17600",
      "p1c"
    ],
    "actionString": "b200b800b2400b9600b20000c///",
    "board": [
      "9H",
      "TH",
      "JH",
      "QH",
      "KH"
    ],
    "__v": 0
  }

**Comment by 2bco** [comment]
Hi Eric , I am very sorry , the erro was mine :  i made a mistake in protocolling the board in case of all in games
