### ISSUE TITLE
Help building local version of API

### ISSUE THREAD

**Issue by nathanielyoon** [ericgjackson/slumbot2019#41]
I want to to compile an instance to call from a bash script, instead of making a network call to the website's API. Is this possible? I've tried the examples in the readme and felt out a few other configurations, but I couldn't figure out how to send input and so on.

**Comment by ericgjackson** [comment]
Slumbot relies on huge data files which are only present on the slumbot.com server.  (I do not share them.)  So I think there is no alternative to using the API.

**Comment by nathanielyoon** [comment]
Alright.
