### ISSUE TITLE
subgame solving

### ISSUE THREAD

**Issue by Kailianghu** [ericgjackson/slumbot2019#6]
Hi, @ericgjackson  Thanks for your open source, you are doing an amazing job!
In slumbot2019/src/#solve_one_subgame_unsafe.cpp#  line 478-481 I notice you have already implemented the unsafe, CFR-D, MaxMargin subgame solving, what is the combined means? I have noticed it is not Noam reach subgame solving, do you have the plan to implement it?

**Comment by ericgjackson** [comment]
I think the MaxMargin resolving is not tested; I wouldn't rely on it

I don't have any time right now to implement Noam's method of resolving.

The combined method is something I came up with.  It's sort of a blend of
unsafe resolving and CFR-D.  It's the best performing method for me.
